export const C = {
  paper: "#F2EFE7",
  ink: "#1B3A8C",
  red: "#C0392B",
  green: "#1B7A3D",
  amber: "#8A6D1D",
  cream: "#FFFDF7",
  line: "#DCE6F5",
  border: "#C9D0E0",
  muted: "#5A6B8C",
  text: "#1D2B50",
};

export const S = {
  app: { maxWidth: 560, margin: "0 auto", minHeight: "100vh", background: C.paper,
    fontFamily: "-apple-system, 'Segoe UI', Roboto, sans-serif", color: C.text, paddingBottom: 76 },
  header: { padding: "16px 16px 8px", display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  logo: { fontSize: 24, fontWeight: 800, letterSpacing: "-0.5px", color: C.ink },
  tagline: { fontSize: 12, color: C.muted, marginTop: 2 },
  viewSwitch: { display: "flex", gap: 4, background: "#fff", border: `1.5px solid ${C.border}`, borderRadius: 8, padding: 2 },
  viewBtn: (on) => ({ padding: "4px 8px", fontSize: 11, fontWeight: 700, border: "none", borderRadius: 6,
    background: on ? C.ink : "transparent", color: on ? "#fff" : C.muted, cursor: "pointer" }),
  main: { padding: "10px 16px 0" },
  label: { display: "block", fontSize: 12, fontWeight: 700, color: C.muted, margin: "12px 0 4px",
    textTransform: "uppercase", letterSpacing: "0.4px" },
  select: { width: "100%", padding: 10, borderRadius: 8, border: `1.5px solid ${C.border}`, fontSize: 14, background: "#fff" },
  textarea: { width: "100%", padding: 10, borderRadius: 8, border: `1.5px solid ${C.border}`, fontSize: 14,
    background: "#fff", boxSizing: "border-box", resize: "vertical" },
  preview: { width: "100%", borderRadius: 8, marginTop: 8, border: `1.5px solid ${C.border}` },
  errorBox: { marginTop: 10, padding: "9px 12px", background: "#FBEAEA", border: "1px solid #E3B4B4",
    borderRadius: 8, fontSize: 13, color: "#8C2B2B" },
  primaryBtn: { width: "100%", marginTop: 14, padding: "13px 0", background: C.ink, color: "#fff",
    fontSize: 15.5, fontWeight: 700, border: "none", borderRadius: 10, cursor: "pointer" },
  ghostBtn: { padding: "10px 16px", background: "#fff", border: `1.5px solid ${C.ink}`, color: C.ink,
    fontWeight: 700, fontSize: 13.5, borderRadius: 8, cursor: "pointer" },
  chip: (bg) => ({ display: "inline-block", minWidth: 22, textAlign: "center", padding: "2px 7px",
    background: bg, color: "#fff", fontWeight: 800, fontSize: 11, borderRadius: 6 }),
  notebook: { display: "flex", marginTop: 16, background: C.cream, border: "1px solid #D8D2C0",
    borderRadius: 6, overflow: "hidden",
    backgroundImage: "repeating-linear-gradient(transparent, transparent 27px, #DCE6F5 27px, #DCE6F5 28px)" },
  margin: { width: 3, background: "#D9534F", marginLeft: 26, flexShrink: 0 },
  page: { padding: "14px 14px 14px 12px", flex: 1 },
  pen: { fontFamily: "'Caveat', cursive", fontSize: 27, fontWeight: 700, lineHeight: 1, marginBottom: 10 },
  rowLabel: { fontSize: 11, fontWeight: 800, textTransform: "uppercase", letterSpacing: "0.5px", marginBottom: 2 },
  rowBody: { fontSize: 14, lineHeight: 1.45 },
  h2: { fontSize: 15, fontWeight: 800, color: C.ink, margin: "8px 0 10px" },
  card: { background: "#fff", border: "1px solid #DDD8C9", borderRadius: 8, padding: "10px 12px", marginBottom: 8 },
  meta: { fontSize: 11.5, color: C.muted, marginBottom: 3 },
  empty: { padding: "22px 16px", textAlign: "center", fontSize: 14, color: C.muted, lineHeight: 1.5 },
  tabbar: { position: "fixed", bottom: 0, left: 0, right: 0, maxWidth: 560, margin: "0 auto",
    display: "flex", background: "#fff", borderTop: `1px solid ${C.border}` },
  tabBtn: (on) => ({ flex: 1, padding: "10px 0 12px", border: "none", background: "none",
    fontSize: 11.5, fontWeight: 700, color: on ? C.ink : C.muted, cursor: "pointer",
    borderTop: `3px solid ${on ? C.ink : "transparent"}` }),
  footer: { padding: "18px 16px 8px", fontSize: 11, color: "#8A8674", lineHeight: 1.5, textAlign: "center" },
  bar: { display: "flex", alignItems: "center", gap: 8, marginBottom: 7 },
  barLabel: { width: 128, fontSize: 12, fontWeight: 600 },
  barTrack: { flex: 1, height: 14, background: "#E4E0D4", borderRadius: 7 },
  barN: { width: 40, fontSize: 12.5, fontWeight: 700, textAlign: "right" },
};

export const CHAPTERS = [
  "Real Numbers", "Polynomials", "Pair of Linear Equations", "Quadratic Equations",
  "Arithmetic Progressions", "Triangles", "Coordinate Geometry", "Introduction to Trigonometry",
  "Heights & Distances", "Circles", "Areas Related to Circles", "Surface Areas & Volumes",
  "Statistics", "Probability",
];

export const ERROR_TYPES = [
  "Sign error", "Transposition", "Calculation slip", "Formula wrong/omitted",
  "Concept gap", "Units / presentation", "Method mismatch",
];
